---
user_pods:
  - name: containerlab
    image: ghcr.io/srl-labs/clab:latest
    network_mode: host
    privileged: true
    restart_policy: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/pods/containerlab/labs:/labs"
      - "/etc/containerlab:/etc/containerlab"
