---
- name: Restart docker service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: restarted

- name: Reload docker service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: reloaded

- name: Prune unused docker resources
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: false
    builder_cache: true
